#!/bin/sh
#
# PROVIDE: xmage
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable this service:
#
# xmage_enable (bool): Set to NO by default.
#
# Set it to YES to enable it.

. /etc/rc.subr
name="xmage"
rcvar="${name}_enable"
load_rc_config $name

: ${xmage_enable:="NO"}
: ${xmage_user:="xmage"}
: ${xmage_chdir:="/usr/local/games/xmage/mage-server"}
: ${xmage_jvmxms:="-Xms256M"}
: ${xmage_jvmxmx:="-Xmx512M"}

pidfile_child="/var/run/${name}.pid"
pidfile="/var/run/${name}_daemon.pid"

command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} -p ${pidfile_child} /usr/local/bin/java ${xmage_jvmxms} ${xmage_jvmxmx} ${xmage_javaopt} -jar ${xmage_javacmd}"
start_precmd="touch ${pidfile}; chown ${xmage_user} ${pidfile}; touch ${pidfile_child}; chown ${xmage_user} ${pidfile_child}"
stop_postcmd="rm ${pidfile}; rm ${pidfile_child}"

run_rc_command "$1"

