#!/bin/sh
#
# PROVIDE: xmage
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable this service:
#
# xmage_enable (bool): Set to NO by default.
#
# Set it to YES to enable it.

. /etc/rc.subr
name="xmage"
rcvar="${name}_enable"
load_rc_config $name

: ${xmage_enable:="NO"}
: ${xmage_user:="xmage"}
: ${xmage_chdir:="/usr/local/games/xmage/mage-server"}
: ${xmage_jvmxms:="-Xms256M"}
: ${xmage_jvmxmx:="-Xmx512M"}
: ${xmage_jvmopt:="-Djava.security.policy=./config/security.policy -Djava.util.logging.config.file=./config/logging.config -Dlog4j.configuration=file:./config/log4j.properties"}

procname="/usr/local/openjdk8-jre/bin/java"
command="/usr/sbin/daemon"
command_args="-f java ${xmage_jvmxms} ${xmage_jvmxmx} -jar ./lib/mage-server-1.4.31.jar"

run_rc_command "$1"

